language: python
python:
  - "3.6"      
  - "3.7"
  - "3.8"
  - "nightly"  
install:
  - pip install antlr4-python3-runtime 
  - pip install coverage
script:
  - python -m unittest tests/runtests.py
